server:
  port: 9999

spring:
  datasource:
    username: USER01
    password: oracle
    url: jdbc:oracle:thin:@//localhost:1521/orcl2
    driver-class-name: oracle.jdbc.driver.OracleDriver

  redis:
    port: 6379
    host: localhost


logging:
  level:
    com.maple: debug
